# Tarea 1 - Pandas

## Análisis de los ingresos presupuestales de los Organismos Públicos Descentralizados del Perú - 2025

In [29]:
import pandas as pd

Importé la librería Pandas porque permite trabajar con bases de datos en Python, facilitando su carga, revisión, limpieza y análisis.

In [30]:
df = pd.read_csv("2025-Ingresos-OPDS.csv")

Cargué la base de datos de ingresos presupuestales del año 2025 y la guardé en un DataFrame llamado `df`, que será la base principal del análisis.

In [31]:
df.head()

,ANO_DOC,MES_DOC,GRUPO_ENTIDAD,GRUPO_ENTIDAD_NOMBRE,SEC_EJEC,EJECUTORA,EJECUTORA_NOMBRE,DEPARTAMENTO_EJECUTORA,DEPARTAMENTO_EJECUTORA_NOMBRE,PROVINCIA_EJECUTORA,...,SUBGENERICA_NOMBRE,SUBGENERICA_DET,SUBGENERICA_DET_NOMBRE,ESPECIFICA,ESPECIFICA_NOMBRE,ESPECIFICA_DET,ESPECIFICA_DET_NOMBRE,MONTO_PIA,MONTO_PIM,MONTO_RECAUDADO
0,2025,8,17,ORGANISMOS PUBLICOS DESCENTRALIZADOS REGIONALES,500108,0,COMITE DE ADMINISTRACIÓN DE LA ZONA FRANCA Y Z...,23,TACNA,1,...,VENTA DE BIENES,3,VENTA DE PRODUCTOS MINERALES,1,VENTA DE PRODUCTOS MINERALES,1,VENTA DE AGUA,0,0,7929.34
1,2025,11,17,ORGANISMOS PUBLICOS DESCENTRALIZADOS REGIONALES,500108,0,COMITE DE ADMINISTRACIÓN DE LA ZONA FRANCA Y Z...,23,TACNA,1,...,VENTA DE SERVICIOS,2,SERVICIOS DE TRANSPORTE Y COMUNICACIONES,1,SERVICIOS DE TRANSPORTE,2,SERVICIOS DE INSPECCION,0,0,0.00
2,2025,5,17,ORGANISMOS PUBLICOS DESCENTRALIZADOS REGIONALES,500108,0,COMITE DE ADMINISTRACIÓN DE LA ZONA FRANCA Y Z...,23,TACNA,1,...,VENTA DE SERVICIOS,2,SERVICIOS DE TRANSPORTE Y COMUNICACIONES,2,SERVICIOS DE COMUNICACIONES,99,OTROS SERVICIOS DE COMUNICACIONES,0,0,19988.99
3,2025,3,17,ORGANISMOS PUBLICOS DESCENTRALIZADOS REGIONALES,500108,0,COMITE DE ADMINISTRACIÓN DE LA ZONA FRANCA Y Z...,23,TACNA,1,...,VENTA DE SERVICIOS,9,OTROS INGRESOS POR PRESTACION DE SERVICIOS,1,SERVICIOS POR ADMINISTRACION Y RECAUDACION,3,SERVICIOS DE ADMINISTRACION,0,0,2603.80
4,2025,1,17,ORGANISMOS PUBLICOS DESCENTRALIZADOS REGIONALES,500108,0,COMITE DE ADMINISTRACION DE LA ZONA FRANCA Y Z...,23,TACNA,1,...,INGRESOS DIVERSOS,1,INGRESOS DIVERSOS,4,OTROS INGRESOS DIVERSOS,99,OTROS INGRESOS DIVERSOS,0,0,7995.52

Mostré las primeras cinco filas para conocer cómo está organizada la base y observar algunas de las variables que contiene.

# 3.1 Pregunta 1: ¿Qué departamentos concentran el mayor monto recaudado?
### Pregunta 1: ¿Qué departamentos concentran el mayor monto recaudado durante 2025?

In [32]:
tabla1 = (
    df.groupby("DEPARTAMENTO_EJECUTORA_NOMBRE", as_index=False)["MONTO_RECAUDADO"]
      .sum()
      .sort_values("MONTO_RECAUDADO", ascending=False)
)

tabla1.head(10)

   DEPARTAMENTO_EJECUTORA_NOMBRE  MONTO_RECAUDADO
7                           LIMA     8.853991e+08
5                    LA LIBERTAD     7.823144e+07
11                         TACNA     4.729373e+07
0                       AREQUIPA     3.985982e+07
9                          PIURA     3.284666e+07
8                       MOQUEGUA     2.321685e+07
6                     LAMBAYEQUE     1.354566e+07
4                          JUNIN     1.341494e+07
2                      CAJAMARCA     9.619961e+06
3                            ICA     9.141446e+06

Agrupé los registros por departamento y sumé el monto recaudado para conocer cuáles concentran los mayores ingresos durante el año 2025. Luego ordené los resultados de mayor a menor y mostré los diez primeros departamentos.

Los resultados muestran que Lima concentra ampliamente el mayor monto recaudado durante 2025. Después aparecen La Libertad, Tacna, Arequipa y Piura, aunque con montos considerablemente menores.

3.2 Pregunta 2: ¿Qué entidades concentran la recaudación dentro de los departamentos con mayores ingresos?

In [33]:
top5_departamentos = tabla1.head(5)["DEPARTAMENTO_EJECUTORA_NOMBRE"]

top5_departamentos

7            LIMA
5     LA LIBERTAD
11          TACNA
0        AREQUIPA
9           PIURA
Name: DEPARTAMENTO_EJECUTORA_NOMBRE, dtype: str

Seleccioné los cinco departamentos con mayor monto recaudado según los resultados de la primera pregunta, para analizar qué entidades explican principalmente esos ingresos.

In [34]:
tabla2 = (
    df[df["DEPARTAMENTO_EJECUTORA_NOMBRE"].isin(top5_departamentos)]
      .groupby(
          ["DEPARTAMENTO_EJECUTORA_NOMBRE", "EJECUTORA_NOMBRE"],
          as_index=False
      )["MONTO_RECAUDADO"]
      .sum()
      .sort_values(
          ["DEPARTAMENTO_EJECUTORA_NOMBRE", "MONTO_RECAUDADO"],
          ascending=[True, False]
      )
)

tabla2

,DEPARTAMENTO_EJECUTORA_NOMBRE,EJECUTORA_NOMBRE,MONTO_RECAUDADO
0,AREQUIPA,ESTABLECIMIENTO DE SALUD MUNICIPAL - ESAMU,2.112765e+07
3,AREQUIPA,ZONA ESPECIAL DE DESARROLLO MATARANI - ZED MAT...,7.738179e+06
1,AREQUIPA,INSTITUTO MUNICIPAL DE PLANEAMIENTO DE AREQUIPA,5.507908e+06
2,AREQUIPA,SERVICIO MUNICIPAL DE ADMINISTRACIÓN DEL MATAD...,5.486082e+06
6,LA LIBERTAD,SERVICIO DE GESTIÓN AMBIENTAL DE TRUJILLO,5.066092e+07
4,LA LIBERTAD,SERVICIO DE ADMINISTRACION TRIBUTARIA DE TRUJILLO,2.260645e+07
5,LA LIBERTAD,SERVICIO DE ADMINISTRACIÓN DE INMUEBLES MUNICI...,3.352466e+06
7,LA LIBERTAD,TRANSPORTES METROPOLITANOS DE TRUJILLO,1.611603e+06
17,LIMA,SISTEMA METROPOLITANO DE LA SOLIDARIDAD - SISOL,3.926018e+08
15,LIMA,SERVICIO DE ADMINISTRACION TRIBUTARIA DE LIMA,1.615221e+08
10,LIMA,FONDO METROPOLITANO DE INVERSIONES DE LIMA,1.473499e+08
16,LIMA,SERVICIO DE PARQUES DE LIMA,7.492848e+07
14,LIMA,PATRONATO DEL PARQUE DE LAS LEYENDAS,6.282875e+07
11,LIMA,HOSPITAL MUNICIPAL DE OLIVOS,2.436745e+07
13,LIMA,INSTITUTO METROPOLITANO DE PLANIFICACION,9.759850e+06
12,LIMA,INSTITUTO CATASTRAL DE LIMA,7.849455e+06
9,LIMA,AUTORIDAD MUNICIPAL DE PROTECCION DE LOS HUMED...,2.515311e+06
8,LIMA,AUTORIDAD DEL PROYECTO COSTA VERDE - APCV,1.676013e+06
20,PIURA,ZONA ESPECIAL DE DESARROLLO PAITA - ZED PAITA,2.058995e+07
18,PIURA,SERVICIO DE ADMINISTRACION TRIBUTARIA DE PIURA,8.307360e+06
19,PIURA,SERVICIO DE ADMINISTRACION TRIBUTARIA DE SULLA...,3.949348e+06
22,TACNA,COMITE DE ADMINISTRACIÓN DE LA ZONA FRANCA Y Z...,4.726919e+07
21,TACNA,COMITE DE ADMINISTRACION DE LA ZONA FRANCA Y Z...,2.453586e+04

Filtré la base para conservar únicamente los cinco departamentos con mayor recaudación y luego agrupé la información por departamento y entidad ejecutora. Esto permite identificar qué organismos aportan los mayores montos recaudados dentro de cada departamento.

In [35]:
tabla2_top3 = (
    tabla2.groupby("DEPARTAMENTO_EJECUTORA_NOMBRE")
          .head(3)
          .reset_index(drop=True)
)

tabla2_top3

,DEPARTAMENTO_EJECUTORA_NOMBRE,EJECUTORA_NOMBRE,MONTO_RECAUDADO
0,AREQUIPA,ESTABLECIMIENTO DE SALUD MUNICIPAL - ESAMU,2.112765e+07
1,AREQUIPA,ZONA ESPECIAL DE DESARROLLO MATARANI - ZED MAT...,7.738179e+06
2,AREQUIPA,INSTITUTO MUNICIPAL DE PLANEAMIENTO DE AREQUIPA,5.507908e+06
3,LA LIBERTAD,SERVICIO DE GESTIÓN AMBIENTAL DE TRUJILLO,5.066092e+07
4,LA LIBERTAD,SERVICIO DE ADMINISTRACION TRIBUTARIA DE TRUJILLO,2.260645e+07
5,LA LIBERTAD,SERVICIO DE ADMINISTRACIÓN DE INMUEBLES MUNICI...,3.352466e+06
6,LIMA,SISTEMA METROPOLITANO DE LA SOLIDARIDAD - SISOL,3.926018e+08
7,LIMA,SERVICIO DE ADMINISTRACION TRIBUTARIA DE LIMA,1.615221e+08
8,LIMA,FONDO METROPOLITANO DE INVERSIONES DE LIMA,1.473499e+08
9,PIURA,ZONA ESPECIAL DE DESARROLLO PAITA - ZED PAITA,2.058995e+07
10,PIURA,SERVICIO DE ADMINISTRACION TRIBUTARIA DE PIURA,8.307360e+06
11,PIURA,SERVICIO DE ADMINISTRACION TRIBUTARIA DE SULLA...,3.949348e+06
12,TACNA,COMITE DE ADMINISTRACIÓN DE LA ZONA FRANCA Y Z...,4.726919e+07
13,TACNA,COMITE DE ADMINISTRACION DE LA ZONA FRANCA Y Z...,2.453586e+04

Para facilitar la lectura, seleccioné las tres entidades con mayor monto recaudado dentro de cada uno de los cinco departamentos analizados.

La tabla permite observar que la recaudación no se distribuye de manera uniforme entre las entidades. En varios departamentos, una pequeña cantidad de organismos concentra una parte importante del monto recaudado.

### Pregunta 3: ¿Cómo evolucionó mensualmente la recaudación en los cinco departamentos con mayores ingresos?

In [36]:
tabla3 = pd.pivot_table(
    df[df["DEPARTAMENTO_EJECUTORA_NOMBRE"].isin(top5_departamentos)],
    index="MES_DOC",
    columns="DEPARTAMENTO_EJECUTORA_NOMBRE",
    values="MONTO_RECAUDADO",
    aggfunc="sum",
    fill_value=0
)

tabla3

DEPARTAMENTO_EJECUTORA_NOMBRE,AREQUIPA,LA LIBERTAD,LIMA,PIURA,TACNA
MES_DOC,,,,,
1,11653816.86,7509299.07,1.698936e+08,13590832.52,32149590.22
2,864347.02,15154497.66,1.137254e+08,2003209.27,1319975.47
3,7536150.79,4773107.77,1.456162e+08,1833684.21,1458978.92
4,2503196.05,5067768.66,5.004806e+07,1603190.53,1624570.69
5,1668587.08,3779615.42,5.015382e+07,1659562.55,1093314.38
6,3234347.72,5965580.04,4.734279e+07,1484566.92,1402231.70
7,1705661.29,3791064.51,4.978811e+07,1278413.66,1100124.42
8,1760314.54,7770019.42,5.387284e+07,2023449.03,1159621.46
9,1758009.02,4322095.75,5.747656e+07,2035601.56,1407509.96
10,1795283.55,4320403.07,5.056511e+07,1887987.36,1432733.16
11,2561607.41,4238212.14,4.717303e+07,1407602.67,1192858.05
12,2818501.37,11539775.81,4.974360e+07,2038555.70,1952220.01

Construí una tabla dinámica para comparar el monto recaudado por mes entre los cinco departamentos con mayor recaudación total. Utilicé los meses como filas y los departamentos como columnas, sumando el monto recaudado en cada caso.

La recaudación presenta variaciones importantes entre los meses. Lima mantiene los mayores montos durante todo el periodo analizado, mientras que en los demás departamentos se observan meses específicos con incrementos más elevados, como enero en Tacna y Piura.

In [37]:
meses = {
    1: "Enero",
    2: "Febrero",
    3: "Marzo",
    4: "Abril",
    5: "Mayo",
    6: "Junio",
    7: "Julio",
    8: "Agosto",
    9: "Septiembre",
    10: "Octubre",
    11: "Noviembre",
    12: "Diciembre"
}

tabla3.index = tabla3.index.map(meses)

tabla3

DEPARTAMENTO_EJECUTORA_NOMBRE,AREQUIPA,LA LIBERTAD,LIMA,PIURA,TACNA
MES_DOC,,,,,
Enero,11653816.86,7509299.07,1.698936e+08,13590832.52,32149590.22
Febrero,864347.02,15154497.66,1.137254e+08,2003209.27,1319975.47
Marzo,7536150.79,4773107.77,1.456162e+08,1833684.21,1458978.92
Abril,2503196.05,5067768.66,5.004806e+07,1603190.53,1624570.69
Mayo,1668587.08,3779615.42,5.015382e+07,1659562.55,1093314.38
Junio,3234347.72,5965580.04,4.734279e+07,1484566.92,1402231.70
Julio,1705661.29,3791064.51,4.978811e+07,1278413.66,1100124.42
Agosto,1760314.54,7770019.42,5.387284e+07,2023449.03,1159621.46
Septiembre,1758009.02,4322095.75,5.747656e+07,2035601.56,1407509.96
Octubre,1795283.55,4320403.07,5.056511e+07,1887987.36,1432733.16
Noviembre,2561607.41,4238212.14,4.717303e+07,1407602.67,1192858.05
Diciembre,2818501.37,11539775.81,4.974360e+07,2038555.70,1952220.01

Reemplacé los números de los meses por sus nombres para que la tabla sea más fácil de interpretar.

Ahora ya tenemos exactamente las tres tablas que después exportaremos al Excel en la Parte5.

In [38]:
tabla1

   DEPARTAMENTO_EJECUTORA_NOMBRE  MONTO_RECAUDADO
7                           LIMA     8.853991e+08
5                    LA LIBERTAD     7.823144e+07
11                         TACNA     4.729373e+07
0                       AREQUIPA     3.985982e+07
9                          PIURA     3.284666e+07
8                       MOQUEGUA     2.321685e+07
6                     LAMBAYEQUE     1.354566e+07
4                          JUNIN     1.341494e+07
2                      CAJAMARCA     9.619961e+06
3                            ICA     9.141446e+06
1                       AYACUCHO     7.579707e+06
10                    SAN MARTIN     2.948818e+06

In [39]:
tabla2_top3

,DEPARTAMENTO_EJECUTORA_NOMBRE,EJECUTORA_NOMBRE,MONTO_RECAUDADO
0,AREQUIPA,ESTABLECIMIENTO DE SALUD MUNICIPAL - ESAMU,2.112765e+07
1,AREQUIPA,ZONA ESPECIAL DE DESARROLLO MATARANI - ZED MAT...,7.738179e+06
2,AREQUIPA,INSTITUTO MUNICIPAL DE PLANEAMIENTO DE AREQUIPA,5.507908e+06
3,LA LIBERTAD,SERVICIO DE GESTIÓN AMBIENTAL DE TRUJILLO,5.066092e+07
4,LA LIBERTAD,SERVICIO DE ADMINISTRACION TRIBUTARIA DE TRUJILLO,2.260645e+07
5,LA LIBERTAD,SERVICIO DE ADMINISTRACIÓN DE INMUEBLES MUNICI...,3.352466e+06
6,LIMA,SISTEMA METROPOLITANO DE LA SOLIDARIDAD - SISOL,3.926018e+08
7,LIMA,SERVICIO DE ADMINISTRACION TRIBUTARIA DE LIMA,1.615221e+08
8,LIMA,FONDO METROPOLITANO DE INVERSIONES DE LIMA,1.473499e+08
9,PIURA,ZONA ESPECIAL DE DESARROLLO PAITA - ZED PAITA,2.058995e+07
10,PIURA,SERVICIO DE ADMINISTRACION TRIBUTARIA DE PIURA,8.307360e+06
11,PIURA,SERVICIO DE ADMINISTRACION TRIBUTARIA DE SULLA...,3.949348e+06
12,TACNA,COMITE DE ADMINISTRACIÓN DE LA ZONA FRANCA Y Z...,4.726919e+07
13,TACNA,COMITE DE ADMINISTRACION DE LA ZONA FRANCA Y Z...,2.453586e+04

In [40]:
tabla3

DEPARTAMENTO_EJECUTORA_NOMBRE,AREQUIPA,LA LIBERTAD,LIMA,PIURA,TACNA
MES_DOC,,,,,
Enero,11653816.86,7509299.07,1.698936e+08,13590832.52,32149590.22
Febrero,864347.02,15154497.66,1.137254e+08,2003209.27,1319975.47
Marzo,7536150.79,4773107.77,1.456162e+08,1833684.21,1458978.92
Abril,2503196.05,5067768.66,5.004806e+07,1603190.53,1624570.69
Mayo,1668587.08,3779615.42,5.015382e+07,1659562.55,1093314.38
Junio,3234347.72,5965580.04,4.734279e+07,1484566.92,1402231.70
Julio,1705661.29,3791064.51,4.978811e+07,1278413.66,1100124.42
Agosto,1760314.54,7770019.42,5.387284e+07,2023449.03,1159621.46
Septiembre,1758009.02,4322095.75,5.747656e+07,2035601.56,1407509.96
Octubre,1795283.55,4320403.07,5.056511e+07,1887987.36,1432733.16
Noviembre,2561607.41,4238212.14,4.717303e+07,1407602.67,1192858.05
Diciembre,2818501.37,11539775.81,4.974360e+07,2038555.70,1952220.01

## 4. Cruce con una segunda fuente

Como segunda fuente se utilizaron las estimaciones de población por departamento del Instituto Nacional de Estadística e Informática (INEI) para el año 2025. Esta información permitirá relacionar el monto recaudado con la cantidad de habitantes de cada departamento.

In [41]:
poblacion_raw = pd.read_excel(
    "poblacion_departamentos_2025.xlsx",
    sheet_name="2024-2026",
    header=None
)

poblacion_raw.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,"POBLACIÓN ESTIMADA AL 30 DE JUNIO, POR AÑOS CA...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ubigeo,Departamento,2024,NaN,NaN,2025,NaN,NaN,2026,NaN,NaN,NaN,NaN
3,NaN,NaN,Total,Hombre,Mujer,Total,Hombre,Mujer,Total,Hombre,Mujer,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,000000,Perú,34038457,16875638,17162819,34350244,17025096,17325148,34660114,17174935,17485179,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,010000,Amazonas,430123,221394,208729,430251,221434,208817,430305,221440,208865,NaN,NaN
8,020000,Áncash,1202171,606821,595350,1205639,608820,596819,1208895,610766,598129,NaN,NaN
9,030000,Apurímac,426626,218675,207951,424906,217893,207013,423128,217081,206047,NaN,NaN

Cargué la hoja correspondiente al periodo 2024-2026 del archivo del INEI para trabajar con la población estimada por departamento del año 2025.

Seleccionamos solo las columnas necesarias

En este Excel, la columna 1 corresponde al departamento y la columna 5 contiene la población total de 2025.

In [42]:
poblacion = poblacion_raw.iloc[5:, [1, 5]].copy()

poblacion.columns = [
    "DEPARTAMENTO",
    "POBLACION_2025"
]

poblacion.head()

  DEPARTAMENTO POBLACION_2025
5         Perú       34350244
6          NaN            NaN
7     Amazonas         430251
8       Áncash        1205639
9     Apurímac         424906

Seleccioné únicamente el nombre del departamento y la población total estimada para 2025, porque son las variables necesarias para realizar el cruce con la base de ingresos.

Eliminamos la fila nacional

El Excel también contiene una fila llamada Perú, pero nosotros necesitamos departamentos:

In [43]:
poblacion = poblacion[
    poblacion["DEPARTAMENTO"] != "Perú"
].copy()

poblacion.head()

   DEPARTAMENTO POBLACION_2025
6           NaN            NaN
7      Amazonas         430251
8        Áncash        1205639
9      Apurímac         424906
10     Arequipa        1631136

Revisamos la base resultante

In [44]:
poblacion.shape

(31, 2)

In [45]:
poblacion.head(10)

                DEPARTAMENTO POBLACION_2025
6                        NaN            NaN
7                   Amazonas         430251
8                     Áncash        1205639
9                   Apurímac         424906
10                  Arequipa        1631136
11                  Ayacucho         669020
12                Cajamarca         1443839
13  Prov. Const. del Callao         1228411
14                     Cusco        1406165
15              Huancavelica         327440

In [46]:
import unicodedata

def quitar_tildes(texto):
    return "".join(
        caracter
        for caracter in unicodedata.normalize("NFD", texto)
        if unicodedata.category(caracter) != "Mn"
    )

Creé una función para eliminar las tildes de los nombres de los departamentos. Esto permitirá que nombres como JUNIN y Junín sean considerados iguales durante el cruce.

In [47]:
poblacion = poblacion.dropna(subset=["DEPARTAMENTO"]).copy()

poblacion = poblacion[
    poblacion["DEPARTAMENTO"] != "Perú"
].copy()

Eliminé las filas vacías y la fila correspondiente al total nacional, ya que para el análisis solo necesito registros a nivel de departamento.

In [48]:
poblacion["DEPARTAMENTO_CLAVE"] = (
    poblacion["DEPARTAMENTO"]
    .str.strip()
    .str.upper()
    .apply(quitar_tildes)
)

In [49]:
recaudacion_departamento = (
    df.groupby(
        "DEPARTAMENTO_EJECUTORA_NOMBRE",
        as_index=False
    )["MONTO_RECAUDADO"]
    .sum()
)

recaudacion_departamento.head()

  DEPARTAMENTO_EJECUTORA_NOMBRE  MONTO_RECAUDADO
0                      AREQUIPA      39859822.70
1                      AYACUCHO       7579707.26
2                     CAJAMARCA       9619961.49
3                           ICA       9141446.44
4                         JUNIN      13414939.11

Agrupé la base de ingresos por departamento y sumé el monto recaudado. Esto permite tener una sola observación por departamento antes de realizar el cruce con la población.

In [50]:
recaudacion_departamento["DEPARTAMENTO_CLAVE"] = (
    recaudacion_departamento["DEPARTAMENTO_EJECUTORA_NOMBRE"]
    .str.strip()
    .str.upper()
    .apply(quitar_tildes)
)

Estandaricé los nombres de los departamentos convirtiéndolos a mayúsculas, eliminando espacios adicionales y retirando las tildes. De esta manera, ambas bases tienen una llave comparable.

### Llave del cruce

La llave utilizada para unir ambas bases es el departamento. En la base de ingresos, la variable original es `DEPARTAMENTO_EJECUTORA_NOMBRE`, mientras que en la base del INEI se denomina `DEPARTAMENTO`.

Para evitar problemas por diferencias en mayúsculas y tildes, se creó en ambas bases una variable estandarizada llamada `DEPARTAMENTO_CLAVE`.

In [51]:
cruce = recaudacion_departamento.merge(
    poblacion[
        [
            "DEPARTAMENTO",
            "POBLACION_2025",
            "DEPARTAMENTO_CLAVE"
        ]
    ],
    on="DEPARTAMENTO_CLAVE",
    how="left",
    indicator=True
)

cruce.head()

,DEPARTAMENTO_EJECUTORA_NOMBRE,MONTO_RECAUDADO,DEPARTAMENTO_CLAVE,DEPARTAMENTO,POBLACION_2025,_merge
0,AREQUIPA,39859822.70,AREQUIPA,Arequipa,1631136,both
1,AYACUCHO,7579707.26,AYACUCHO,Ayacucho,669020,both
2,CAJAMARCA,9619961.49,CAJAMARCA,Cajamarca,1443839,both
3,ICA,9141446.44,ICA,Ica,1083566,both
4,JUNIN,13414939.11,JUNIN,Junín,1383107,both

Realicé un cruce de tipo left para conservar todos los departamentos de la base de ingresos y agregar la población estimada del INEI cuando exista coincidencia. También utilicé un indicador para verificar el resultado del cruce.

In [52]:
cruce["_merge"].value_counts()

_merge
both          12
left_only      0
right_only     0
Name: count, dtype: int64

Los 12 departamentos presentes en la base de ingresos encontraron correspondencia en la base del INEI. No quedaron registros sin cruzar después de estandarizar los nombres de los departamentos.

Creamos la variable que necesita ambas fuentes

Ahora vamos a responder nuestra pregunta:

¿Cuánto ingreso recaudado corresponde por habitante en cada departamento?

In [53]:
cruce["POBLACION_2025"] = pd.to_numeric(
    cruce["POBLACION_2025"]
)

In [54]:
cruce["RECAUDACION_POR_HABITANTE"] = (
    cruce["MONTO_RECAUDADO"]
    / cruce["POBLACION_2025"]
)

Calculé la recaudación por habitante dividiendo el monto total recaudado de cada departamento entre su población estimada para 2025. Este indicador solo puede obtenerse al combinar la información de las dos fuentes.

## Tabla final

In [55]:
tabla_cruce = (
    cruce[
        [
            "DEPARTAMENTO_EJECUTORA_NOMBRE",
            "MONTO_RECAUDADO",
            "POBLACION_2025",
            "RECAUDACION_POR_HABITANTE"
        ]
    ]
    .sort_values(
        "RECAUDACION_POR_HABITANTE",
        ascending=False
    )
    .reset_index(drop=True)
)

tabla_cruce

,DEPARTAMENTO_EJECUTORA_NOMBRE,MONTO_RECAUDADO,POBLACION_2025,RECAUDACION_POR_HABITANTE
0,TACNA,4.729373e+07,402089,117.620050
1,MOQUEGUA,2.321685e+07,202946,114.399141
2,LIMA,8.853991e+08,11461995,77.246505
3,LA LIBERTAD,7.823144e+07,2155943,36.286414
4,AREQUIPA,3.985982e+07,1631136,24.436848
5,PIURA,3.284666e+07,2172710,15.117828
6,AYACUCHO,7.579707e+06,669020,11.329568
7,LAMBAYEQUE,1.354566e+07,1372301,9.870764
8,JUNIN,1.341494e+07,1383107,9.699133
9,ICA,9.141446e+06,1083566,8.436446
10,CAJAMARCA,9.619961e+06,1443839,6.662766
11,SAN MARTIN,2.948818e+06,955789,3.085219

Organicé la tabla final de mayor a menor según la recaudación por habitante. De esta manera se puede comparar la recaudación de los departamentos teniendo en cuenta el tamaño de su población.

In [56]:
tabla_cruce["RECAUDACION_POR_HABITANTE"] = (
    tabla_cruce["RECAUDACION_POR_HABITANTE"].round(2)
)

tabla_cruce

,DEPARTAMENTO_EJECUTORA_NOMBRE,MONTO_RECAUDADO,POBLACION_2025,RECAUDACION_POR_HABITANTE
0,TACNA,4.729373e+07,402089,117.62
1,MOQUEGUA,2.321685e+07,202946,114.40
2,LIMA,8.853991e+08,11461995,77.25
3,LA LIBERTAD,7.823144e+07,2155943,36.29
4,AREQUIPA,3.985982e+07,1631136,24.44
5,PIURA,3.284666e+07,2172710,15.12
6,AYACUCHO,7.579707e+06,669020,11.33
7,LAMBAYEQUE,1.354566e+07,1372301,9.87
8,JUNIN,1.341494e+07,1383107,9.70
9,ICA,9.141446e+06,1083566,8.44
10,CAJAMARCA,9.619961e+06,1443839,6.66
11,SAN MARTIN,2.948818e+06,955789,3.09

Redondeé la recaudación por habitante a dos decimales para facilitar la lectura e interpretación de los resultados.

5. Exportar las tres tablas

In [57]:
with pd.ExcelWriter("resultados_tarea1.xlsx") as writer:
    tabla1.to_excel(
        writer,
        sheet_name="Pregunta 1",
        index=False
    )

    tabla2_top3.to_excel(
        writer,
        sheet_name="Pregunta 2",
        index=False
    )

    tabla3.to_excel(
        writer,
        sheet_name="Pregunta 3"
    )

Comprobamos que el archivo fue creado

In [58]:
import os

os.path.exists("resultados_tarea1.xlsx")

True